const NAVIGATION_ROUTES = {
  WEATHER_TABS: 'WEATHER_TABS',
  WEATHER_STACK: 'WEATHER_STACK',
  WEATHER_DETAILS: 'WEATHER_DETAILS',
  DAY_SELECTION: 'DAY_SELECTION',
  CITY_SELECTION: 'CITY_SELECTION',
  LOGIN: 'LOGIN',
  SETTINGS: 'SETTINGS',
} as const;

export default NAVIGATION_ROUTES;
