const NAVIGATION_ROUTES = {
  WEATHER_STACK: 'WEATHER_STACK',
  WEATHER_DETAILS: 'WEATHER_DETAILS',
  DAY_SELECTION: 'DAY_SELECTION',
  CITY_SELECTION: 'CITY_SELECTION',
  LOGIN: 'LOGIN',
  SETTINGS: 'SETTING',
};

export default NAVIGATION_ROUTES;
