export const USER_ACTIONS = {
  SET_HAS_INVALID_LOGIN_ATTEMPT: 'SET_HAS_INVALID_LOGIN_ATTEMPT',
  SET_IS_AUTHORIZATION_IN_PROGRESS: 'SET_IS_AUTHORIZATION_IN_PROGRESS',
  SET_IS_AUTHORIZED: 'SET_IS_AUTHORIZED',
  REQUEST_SIGN_IN: 'REQUEST_SIGN_IN',
};

//const WEATHER_ACTIONS_PREFIX = '';
export const WEATHER_ACTIONS = {
  SET_IS_FETCHING: 'SET_IS_FETCHING',
  SET_WEATHER: 'SET_WEATHER',
  FETCH_WEATHER: 'FETCH_WEATHER',
};
