export const USER_ACTIONS = {
  SET_HAS_INVALID_LOGIN_ATTEMPT: 'SET_HAS_INVALID_LOGIN_ATTEMPT',
  SET_IS_AUTHORIZATION_IN_PROGRESS: 'SET_IS_AUTHORIZATION_IN_PROGRESS',
  SET_IS_AUTHORIZED: 'SET_IS_AUTHORIZED',
  REQUEST_SIGN_IN: 'REQUEST_SIGN_IN',
};
